### ISSUE TITLE
Loading model with more than one parameter on Windows hangs forever

### ISSUE THREAD

**Issue by danielhers** [clab/dynet#1010]
Using Python 3.6 on Windows 7 64bit, I'm saving a very small model but loading it never ends (I waited half an hour before killing it):

    import sys
    import dynet as dy
    m = dy.ParameterCollection()
    p = [m.add_parameters(1), m.add_parameters(1)]
    print("Saving model...", file=sys.stderr)
    dy.save("test_model", p)
    print("Loading model...", file=sys.stderr)
    dy.load("test_model", m)
    print("Done", file=sys.stderr)

If the model has just one parameter, it works, but adding the second parameter makes it hang.

**Comment by danielhers** [comment]
@mattr1 maybe it's related to the infinite loop you mentioned in 2ce679b0b328b8b5e3c8c700f00fb804728a0701...

**Comment by chunyang-wen** [comment]
Hi, would please test master branch of this repo?

https://github.com/chunyang-wen/dynet

I think the problem is caused by "\n" -- "\r\n" under windows. I have no windows machine.

**Comment by mattr1** [comment]
I can take a look at this. I also thought the problem was \r\n vs. \n, but stripping the \r's from the test input file didn't fix the problem. I'll test your changes and see if that helps, but it still leaves a bit of a problem in that when you move files around, sometimes \n's are replaced with \r\n. For instance, the model files checked in to git might get \r's inserted in them if git decided it was a text file rather than binary file (not sure how git decides what the file type is). 

I think the problem is caused by the reader seeking forward in the file some set number of bytes (specified on a given line). I don't see any reason for this rather than just reading the line, except maybe an argument of efficiency. I think it's a little dangerous to have the model file look pretty much like a nice text file, with newlines and readable numbers, but then have byte seeking offsets integrated in it. If we change this to advance by reading a line then people could actually edit the file if they wanted.

**Comment by chunyang-wen** [comment]
I just make the file as binary format when reading and writing. Then \n \r\n won't happen. And it is also readable I think.

**Comment by chunyang-wen** [comment]
The reason to seek around is that we can load part of a saved model. Bytes shift is needed when skipping otherwise we have to read everything. I think current loader is a little inefficient because frequent creation and destruction of file stream. I will try to figure out if there exists any better way.

**Comment by mattr1** [comment]
Okay, your changes worked in Windows, both with the test-io unit test, and the python script above. Can you do a pull request to merge them in?

There's still a big danger with using newlines and assuming they will stay a single character. Git automatically converts LF to CR-LF on Windows machines, so if for instance anyone is working in Windows and checks in a model, then it will become unusable. I'll just file an issue about this bug. Changing to readline shouldn't have any performance penalty unless lines >1MB since seeking takes about as long as it takes to read 1MB of data anyway.

**Comment by chunyang-wen** [comment]
Thanks, sure. Working on.

**Comment by chunyang-wen** [comment]
@mattr1 If we create the file stream as `std::ios_base::binary`, then there will be no more automatic conversion between "\n" and "\r\n". Our calculation of bytes is correct and we can safely skip bytes. By the way, I think the binary format is still readable.

**Comment by mattr1** [comment]
@chunyang-wen I'm sorry, we seem to be miscommunicating. I agree that the file is created properly with your changes. My concern is other unrelated programs, such as _git_ that automatically replace LF with CRLF on Windows. The scenario I'm describing is, for example, suppose you and I are working on a paper and using github as a repository. If you train a model and push it to github, and then I pull that model to my Windows machine, I will not be able to load it because git will convert the LFs to CR-LFs (under the default git installation settings). Your change is good and necessary, but I also think it's good longer-term to change it to be robust to such accidental CR injection.

**Comment by danielhers** [comment]
Fixed by #1014. Please open another issue about the newline type robustness, if you want.
