### ISSUE TITLE
Turn broadcasting off by default?

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1016]
Currently many operations in DyNet use broadcasting by default (e.g. `+`, `-`, `cmult`, `cdiv`). This can be a source of bugs when you do broadcasting but didn't think that you did. I propose that we turn broadcasting off by default, but add a flag that makes it possible to enable it.

**Comment by chunyang-wen** [comment]
Like numpy, TensorFlow, it is turned on by default. If we turn it off by default, maybe it will incur more complaint?

**Comment by pmichel31415** [comment]
I agree that it would be good to have as an option but I think it should be enabled by default and disabled for debugging.

**Comment by neubig** [comment]
Hmm, but the people that have the most trouble with this are the users who don't realize that broadcasting is happening. I can see arguments both ways. Either way, it should certainly be added as an option.

**Comment by danielhers** [comment]
Just for comparison, TensorFlow doesn't seem to let you disable broadcasting, but has extra checks in error-prone cases, e.g. tensorflow/tensorflow#1406. And I couldn't even find a numpy flag to disable broadcasting, except for the `no_broadcast` flag in [`nditer`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.nditer.html)...

**Comment by mattr1** [comment]
I would also vote for broadcasting to be off by default and turned on by an option. The option should be trivial to enable in code, so that those who do a lot of broadcasting can just turn it on there instead of on the command line. 

But I understand that maybe it will make people think dynet is weaker than other packages. One way to alleviate this could be that when a computation graph build fails because of dimensionality mismatch, but would have succeeded with broadcasting, the error message can just say something like "if you intended this operation to broadcast, you can turn that on with such and such option". 

Also, when broadcasting is turned off, it would be good to be able to enable it for single operations. Not sure how to make that look reasonable in the code though. I guess it could be a local property of the computationGraph that I could turn on, add my expression, then turn back off.

**Comment by redpony** [comment]
+1 for turning off broadcasting for non-scalar operations, but we need a way to turn on broadcasting without a performance penalty (and, hopefully, without syntax that is too cumbersome).
