### ISSUE TITLE
Running in Python on Windows requires CUDA libraries to be in the PATH

### ISSUE THREAD

**Issue by Alexir** [clab/dynet#1017]
Short version: dynet builds ok for the CPU version but fails for the CUDA version, on Windows.
Following the instructions at http://dynet.readthedocs.io/en/latest/python.html#windows-python-install 

cpu build:
g:\Software\dynet-base\dynet\build>"c:\Program Files\CMake\bin\cmake.exe" .. -G"Visual Studio 15 2017 Win64" -DEIGEN3_INCLUDE_DIR=g:/Software/dynet-base/eigen

But if i go on to add cuda (using cudnn-8.0-windows10-x64-v6.0), with
g:\Software\dynet-base\dynet\build>"c:\Program Files\CMake\bin\cmake.exe" .. -DEIGEN3_INCLUDE_DIR=G:/Software/dynet-base/eigen -DPYTHON=C:/Anaconda3/python.exe -DBACKEND=cuda -DCUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0" -G"Visual Studio 15 2017 Win64"

It breaks. The cmake works but the .sln doesn't. I get the following error(s):
2>------ Rebuild All started: Project: dynet, Configuration: Release x64 ------
2>Building NVCC (Device) object dynet/CMakeFiles/dynet.dir/Release/dynet_generated_cudnn-ops.cu.obj
2>Failed to run C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/bin (The system cannot find the file specified.
2>
2>).
2>CMake Error at dynet_generated_cudnn-ops.cu.obj.Release.cmake:215 (message):
2>  Error generating
2>  G:/Software/dynet-base/dynet/build/dynet/CMakeFiles/dynet.dir//Release/dynet_generated_cudnn-ops.cu.obj
2>
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
2>Done building project "dynet.vcxproj" -- FAILED.

searching for the error string finds similar issues for https://github.com/davisking/dlib (for what that's worth)

**Comment by neubig** [comment]
I don't have a windows environment to debug, but @mattr1 have you experienced this on Windows?

**Comment by mattr1** [comment]
I haven't experienced a problem, but there are a few things here to try that I notice as differences between my compile and yours:
- Can you try installing CUDNN and add something like -DCUDNN_ROOT="c:/libs/cudnn-8.0-windows10-x64-v5.1" to the cmake command line. Supposedly CUDNN isn't required, but it looks like it's trying to compile the CUDNN object file, so this is worth a try. I just tried without CUDNN and it compiles for me, but perhaps it's due to a compiler version difference.
- So far, I've only verified that it builds in VS2015. A few months ago I tried VS2017 and ran into problems (I think with python). If you have VS2015, it's also worth a try. 
- You could try letting Cmake automatically find CUDA instead of specifying where it is on the cmake command line. Or maybe it needs to point to the /bin directory or something?
- Finally, you are adding CUDA and python at the same time. Can you try doing CUDA without Python to confirm you have the same problem (I'm sure you will, but might as well tackle one problem at a time). 

Also, I think cmake generates logs of the compile, you might be able to find a log with more error message details. You can also paste what cmake says here, it might help see a problem.

**Comment by Alexir** [comment]
So there is one cmake error, as follows:

-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0
(found version "8.0")
CUDA_LIBRARIES: C:/Program Files/NVIDIA GPU Computing
Toolkit/CUDA/v8.0/lib/x64/cudart_static.lib
-- Found CUDNN (include: G:/Software/NVidia/cuda/include, library:
G:/Software/NVidia/cuda/lib/x64/cudnn.lib)
-- Successfully include CUDNN flags
-- Eigen dir is G:/Software/dynet-base/eigen
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found Cython version 0.26

It looks like I was ignoring it because of the line right after (which, on
reflection, is probably to do with something else).

Anyway, I do have a pthreads package lying around. Where would I stick it
in? (assuming that's the issue.)

Alex

**Comment by mattr1** [comment]
The pthreads thing is ignorable. I'm actually not sure why it looks for pthreads at all, it is something historic that you can ignore. 

It turns out I also can't compile on VS2017. The reason is that CUDA 8.0 doesn't support VS2017 (see https://devtalk.nvidia.com/default/topic/997997/cuda-support-for-visual-studio-2017/). You'll have to either use VS2015 or install CUDA 9.0. As far as I am aware, dynet has not yet been tested to see if it'll compile with CUDA 9.0 in VS2017. If you go this route, please report back and let us know if you are able to get it to work!

**Comment by mattr1** [comment]
In fact, there's a related issue https://github.com/clab/dynet/issues/988 that says that Eigen is not compiling properly with CUDA 9.0 (on Linux at least). Still worth trying on Windows to see if there are different problems.

**Comment by Alexir** [comment]
ok, CDUA 9.0 (still) doesn't work; use 8.0. You indeed have to use VS 14 2015; VS 15 fails.
cmake needs the PYTHON flag because it has a check for Cython that invokes python.
Given all that, dynet builds (though there's that complaint about pthread.h).
However python isn't importing:

g:\Software\dynet-base\dynet\build\python>python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dynet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "g:\Software\dynet-base\dynet\build\python\dynet.py", line 15, in <module>
    from _dynet import *
ImportError: DLL load failed: The specified module could not be found.
>>> quit()

There's the following which shows up when I build in the IDE, but it doesn't seem relevant:
4>  --- Logging error ---
4>  Traceback (most recent call last):
4>    File "C:\Users\air\AppData\Local\Continuum\Anaconda3\lib\logging\__init__.py", line 994, in emit
4>      stream.write(msg)
4>  ValueError: underlying buffer has been detached
4>  Call stack:
4>    File "G:/Software/dynet-base/dynet/setup.py", line 373, in <module>
4>      data_files=[("../..", DATA_FILES)],
4>    File "C:\Users\air\AppData\Local\Continuum\Anaconda3\lib\distutils\core.py", line 148, in setup
4>      dist.run_commands()
4>    File "C:\Users\air\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
4>      self.run_command(cmd)
4>    File "C:\Users\air\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 974, in run_command
4>      cmd_obj.run()
4>    File "G:/Software/dynet-base/dynet/setup.py", line 320, in run
4>      log.info("Copying built extensions...")
4>  Message: 'Copying built extensions...'
4>  Arguments: ()

FYI, I'm also attaching the .bat script I'm using for the build. In case it's useful, here's what's in the build/python/ folder (note there''s no .dll.) 

air@RAMPU /cygdrive/g/Software/dynet-base/dynet/build/python
$ ls
__pycache__                dynet_viz.py
_dynet.cp36-win_amd64.pyd  INSTALL.vcxproj
_dynet.cpp                 INSTALL.vcxproj.filters
_dynet.pxd                 pydynet.vcxproj
_dynet.pyx                 pydynet.vcxproj.filters
build                      pydynet.vcxproj.user
cmake_install.cmake        pydynet_precopy.vcxproj
CMakeFiles                 pydynet_precopy.vcxproj.filters
dynet.py                   timestamp
dynet.py.in                x64
dynet_config.py

[build.bat.txt](https://github.com/clab/dynet/files/1423251/build.bat.txt)

**Comment by mattr1** [comment]
I don't know much about the python importing, I use C++ instead. It would be nice if we knew which DLL it failed to load. I wonder if it's failing to load one of the CUDA DLLs. Looking in my path, I have C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin and C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp in my PATH environment variable, can you try adding those? Also probably irrelevant but I see I also have "CUDA_PATH" and "CUDA_PATH_V8_0" set to "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0". 

Also, can you say more about what happens if you don't define -DPYTHON? Looking at the python\CMakeLists.txt, it should only check the Cython version if PYTHON is defined. If we get an error when python is not defined, that should be filed as a bug and fixed.

**Comment by mattr1** [comment]
Okay, yep, I just tried removing the CUDA directory from my PATH and I get the same error when importing for python, so I'm 99% sure this will fix your problem.

**Comment by Alexir** [comment]
Thanks! I'll have a chance to play with this late tomorrow; will post the
outcome.


I did get a chance to poke around a bit earlier today.
That error message shows up on the interweb, mostly associated with
tensorflow + cuda problems. Which was a good sign.
So I rechecked my paths (CUDA_PATH_V8.0, CUDNN_ROOT): no luck. But I now
see that I don't have libnvvp in there.
FWIW, I tried a 'python -v -v -v' run but it wasn't informative. Next up
was going to be 'python -m pdb'.

Alex

**Comment by Alexir** [comment]
mattr1's suggestion fixes the problem!
In the process of figuring this out I made use of the following .bat file that does the whole build; if you have problems with it, let me know. 

:: Build a CUDA-enabled dynet on Windows (10) x64
:: This is for VS 14 2015
:: Based on the instructions at http://dynet.readthedocs.io/en/latest/python.html
:: [20171026] (air)
::

:: As *ADMINISTRATOR*, open a 'VS2015 x64 Native Tools Command Prompt'
:: cd to <dynet-root>\dynet\build\

:: change these to point to your own installations (also some others in the cmake)
set NVID="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0"
set PYTH="C:\Users\air\AppData\Local\Continuum\Anaconda3\python.exe"

set PATH=%NVID%\bin;%PATH%

:: clean up previous state
if exist "CMakeCache.txt" del "CMakeCache.txt"
if exist "dynet.sln" del "dynet.sln"

echo. & echo ----- RUN CMAKE TO GENERATE A .sln -----
"c:\Program Files\CMake\bin\cmake.exe" .. ^
    -G"Visual Studio 14 2015 Win64" ^
    -DPYTHON=%PYTH% ^
    -DEIGEN3_INCLUDE_DIR="G:/Software/dynet-base/eigen" ^
    -DBACKEND=cuda ^
    -DCUDA_TOOLKIT_ROOT_DIR=%NVID:\=/% ^
    -DCUDNN_ROOT="G:/Software/NVidia/cuda"

echo. & echo ----- (re)BUILD THE SOLUTION - Release config -----
set VS90COMNTOOLS=%VS140COMNTOOLS%
devenv.exe dynet.sln /Rebuild Release

echo. & echo ----- TEST THE PYTHON DYNET INSTALL -----
cd python & %PYTH% -c "print('Attempting dynet import...');import dynet"
if "%errorlevel%" equ "0" ( echo Build SUCCEEDED! ) else ( echo Build FAILED! )
cd ..
::

**Comment by mattr1** [comment]
I'm going to close this issue. The final conclusion was to make sure the CUDA libraries are in the PATH. I'll add this note to the Windows installation instructions. @neubig , if the CUDA libraries need to be in the PATH for python to work on Linux also, let me know and we can add them in some more generic installation section instead.

**Comment by mattr1** [comment]
Closed with https://github.com/clab/dynet/commit/960e558e3e9a05896c3ffacd618dbb9b2dd1cce4.
