### ISSUE TITLE
Memory allocated twice when using GPU?

### ISSUE THREAD

**Issue by katadh** [clab/dynet#1018]
Hi, I'm having an issue where when using dynet with the GPU setting the memory causes the amount of memory I set to be allocated on both VRAM and RAM.

So for example my configuration looks like this:

    import dynet_config
    dynet_config.set_gpu()
    dynet_config.set(mem=2000, requested_gpus=1, autobatch=True)
    import dynet

And the system monitor shows 2GB of RAM has been allocated and nvidia-smi shows that 2GB of VRAM has been allocated. I am using Ubuntu 16.04 and I have the most recent version of dynet from pip as of a couple days ago.

**Comment by neubig** [comment]
@xunzhang: is this an artifact of the new multi-device interface? Is there any way around this?

@katadh: Can you try setting `mem=1` (or maybe `mem=4`) and see if it works?

**Comment by katadh** [comment]
I get:

    terminate called after throwing an instance of 'std::invalid_argument'
      what():  Dynet does not support both dynamic increasing of memory pool size, and automatic batching or memory checkpointing. If you want to use automatic batching or checkpointing, please pre-allocate enough memory using the --dynet-mem command line option (details http://dynet.readthedocs.io/en/latest/commandline.html).
    Aborted (core dumped)

If I turn off autobatching then I can see the memory increasing in both places as the model starts to run. Although its hard to tell if they both increase by the same amount.

**Comment by xunzhang** [comment]
@katadh Hi, for your original question, currently if you use GPU, DyNet will add a CPU device behind the screen. I think it might change the previous behavior, I can fix it very soon. And since under the multi-device case, we will specify all of the devices' memory using the same memory argument(this seems incorrect for now and ideally we need a list-like argument).

BTW, the line of `dynet_config.set_gpu()` is redundant since you have `dynet_config.set(requested_gpus=1)` already.

**Comment by neubig** [comment]
I think this is fixed.
