### ISSUE TITLE
Displaying memory pool information

### ISSUE THREAD

**Issue by jeticg** [clab/dynet#1137]
As I understand dynet maintains 4 memory pools for forward pass, backward pass, parameters, and scratch. But sometimes individual models may vary in construction, and thus making memory demand for each pool potentially different. As models grow big, since the GPU memory is relatively limited, it would be nice to know when dynet is "out of memory", which pool exactly is using more memory than the others, so that one can adjust the size for each memory pool manually.

**Comment by xunzhang** [comment]
I'll add this.

**Comment by jeticg** [comment]
Thanks! But I tried the above pull request, it does not seem to address the issue for Python.

**Comment by xunzhang** [comment]
You are right. The GPU malloc issue is caught by `CUDA_CHECK` already, I need to add the profiling function there too. See my coming pull request, please.

For the CPU memory allocation, the `__mm_malloc` will not return an empty pointer since Linux uses the optimistic memory allocation strategy, it will break when DyNet uses the actual out-of-memory address (e.g. `memset`). But I think it's a different issue though.

**Comment by jeticg** [comment]
Resolved by #1141. Closing.
