### ISSUE TITLE
Is there a plan to add C++ optimized CRF loss in Dynet?

### ISSUE THREAD

**Issue by ChijunZhang** [clab/dynet#1164]
As CRF loss function is used frequently in NLP, maybe it`s good to officially support CRF layer(include Viterbi decoder) under C++ level in Dynet.

**Comment by redpony** [comment]
Generally, CRF losses are implemented using the DyNet primitives by the
caller in the host level since DyNet's overhead is supposed to be low,
making this feasible (although Python is extremely slow, so using one of
the other host languages is a better bet for things like CRFs).
Furthermore, there are problems with providing a specialized "Node"
implementation of the CRF loss. First, there are many CRFs- linear chain as
well as more general graphical structures. Even if you want to target just
sequence labeling problems, what is the clique structure? Second, how do
you represent the “supervision”? With a single gold structure? Or do you
require the caller to provide posterior distribution targets? (This is a
bit like the difference between "pickneglogsoftmax" and computing the cross
entropy KL between a target distribution on outputs and the modeled
distribution- that way you can back prop into both.)

Because there are not really obvious default answers to these questions
(people who want "structured attention", as has been proposed a couple
times in the last year, would not want to be constrained just to have
target sequences), and because DyNet is designed to give you the primitives
you need to implement a CRF, my feeling is that it does not make sense for
us to include a primitive "CRF loss" node in the core library. However, I
do think in performance critical applications, being able to write custom
code for things like this would be useful, and, in particular, it would
nice to be able to add "third party nodes" that individual projects could
define, as well as possibly a library of reference implementations for
things like basic linear chain CRF losses with single sequence supervision.
The problem is: currently, nodes are defined in exactly one place-- inside
the core library.

Making "third party" nodes accessible from C++ host programs is easy enough
since C++ is always compiled and linked against many libraries, so you
could have the core dynet library, and then any additional libraries of
nodes (although there would be some problems with adding autobatching since
the core library maintains a list of all the batchable types). But, making
third party nodes visible in Python (where you would really want them
because it would let you address Python's slowness with fast C++ code),
would be non trivial. Right now, for every node type, we write a lot of
boilerplate in a single monolithic Cython file, and there is a bunch of
internal state that the Python library maintains that lives just in that
file. There probably is a design that would let you have more dynamic nodes
(even if you still had to cythonize your own code), but this is far from
where we are right now. But, if we want to get serious about letting people
implement CRF nodes and accessing them from Python, this is the direction
DyNet needs to take.

**Comment by ChijunZhang** [comment]
Thanks a lot for the detailed reply.
At fist I only targeted the special case of linear-chain CRF for sequence labeling tasks.In this scenario, user gives a list of unary scores , corresponding tag indices and an optional transition parameter, then a optimized "CRF node" take care of the computation and return the log-likelihood.
It is very helpful to know the internal mechanism about Dynet. After learning deeper about it, I`ll try to implement  "linear-chain CRF loss" node with C++.
