### ISSUE TITLE
Multi GPUs for LSTMs?

### ISSUE THREAD

**Issue by supakjk** [clab/dynet#1172]
Is there a plan to enable using multiple GPUs for LSTMs for parallelization?

**Comment by neubig** [comment]
You can already put the parameters/computation on multiple GPUs using DyNet's multi-GPU support, but this computation will not be run in parallel. In order to run this in parallel, we will need to implement execution of the graph using multiple threads here https://github.com/clab/dynet/issues/33

This is non-trivial, so it may take some time, but it's something relatively high on the priority list.
