### ISSUE TITLE
Tests are failing with recent commit

### ISSUE THREAD

**Issue by pmichel31415** [clab/dynet#1190]
I think df20bc09cdbfacc577e3378f1d863241b20230c6 might have broken some nodes, test-nodes seem to be failing since.

**Comment by neubig** [comment]
I've identified the problem and will send a fix shortly.

**Comment by neubig** [comment]
Should be fixed by this: https://github.com/clab/dynet/pull/1191

@redpony  Apparently defining intermediate variables with "auto" works on linux but not on mac. In general it feels a bit dangerous though, as we can't really tell where memory is going to be allocated. Things like this should probably run tests, and also be run on GPU to make sure they work there (if they weren't already).
