### ISSUE TITLE
AmsgradTrainer documented, but not in the latest training.h

### ISSUE THREAD

**Issue by slaweks17** [clab/dynet#1238]
Hi,
I can't find it.

Regards,
Slawek

**Comment by xunzhang** [comment]
It's in latest master https://github.com/clab/dynet/blob/master/dynet/training.h#L465. The document is for the latest master. I think your problem is you may use v2.0.2 or v2.0.1 and read a mismatched document.

@neubig I think we need to freeze a readthedoc version when making a release in the future.

**Comment by slaweks17** [comment]
Hi,
But how do I get it? When I do
git clone https://github.com/clab/dynet.git
I am not getting it.

When I follow with
git checkout tags/v2.0
I am also not getting it.

Regards,
Slawek

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
