### ISSUE TITLE
Update LSTM's parameters from another LSTM's parameters

### ISSUE THREAD

**Issue by Cartus** [clab/dynet#1255]
Hi,

I have a question. Under some circumstances, like in Reinforcement Learning. I have a Policy Network and a Rollout Network. The parameters of the Rollout Network is the same as the Policy Network. Then we used the Rollout Network the get rewards in order to update parameters of Policy Network by using Policy Gradient Methods.

After that, we also need to update parameters of the Rollout Network by using an update rate. For example:
Theta of Rollout Network <-  Theta of Rollout Network +  update_rate * Policy Network

However, we can not load parameters for LSTM builders. I want to ask if there is a way to do this in Dynet. I am using Stack LSTM as the Policy Network.

**Comment by neubig** [comment]
Is this Python or C++ DyNet? This isn't a natural use case that DyNet supports well, but if you're using C++ (which I guess because you're using Stack LSTM) you could probably get the ParameterCollection  for the LSTM builder, and do the update yourself with some of the methods in ParameterCollection: http://dynet.readthedocs.io/en/latest/core.html#_CPPv3N5dynet19ParameterCollectionE

**Comment by neubig** [comment]
(I'm going to close this issue because this is probably not something that we're going to support any more than this, but if you find an example of how to do this I think others would appreciate if you could post it here)
