### ISSUE TITLE
Better mini-batching documentation regarding dimensions

### ISSUE THREAD

**Issue by talbaumel** [clab/dynet#248]
I'm trying to create an attention based RNN that uses batches
But I'm having a weird multiplication error

_attention_weights = matrix size of lstm_length*batch_size
input_vectors = a lstm_length items list each item is state_size*batch_size_

When running the following code:
output_vecs = [vector*attention_weights[i, batch_len] for i, vector in enumerate(input_vectors)]
I get the error:
_libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: Mismatched input dimensions in MatrixMultiply: [{10X2} {2X2}]_

As far as I can tell [{10X2} {2X2}] are matching
Any ideas?
Thanks, Tal

**Comment by neubig** [comment]
First, I've added some slightly better doc on minibatching, so please take a look here, this may clear things up and solve your problem:
http://dynet.readthedocs.io/en/latest/minibatch.html

As a separate problem, this error message is confusing because the description of the dimensions is not very verbose. `{10x2}` actually means "a length 10 vector over two sentence", while you're interpreting it to mean "a 10 by 2 matrix," which is notated `{10,2}`. This needs to be documented somewhere, so I'll mark this a bug and change the title appropriately.

**Comment by talbaumel** [comment]
Thanks, any idea how I can multiply them?
When iterating over _attention_weights_ I received a vector of correct length but only one value was correct and the were zeros

Example:
_[a.npvalue() for i,a in zip(input_vectors, attention_weights)]_
Will return:
_<class 'list'>: [array([[ 0.46245694,  0.        ]]), array([[ 0.53754306,  0.        ]])]_
When _attention_weights_ doesn't contain any zeros

**Comment by neubig** [comment]
The issue of the doc should be updated here: https://github.com/clab/dynet/commit/f9481829e80ffee418ec81ba9084286d3b67d9ab

With regards to the problem of multiplication, basically I would recommend implementing the attention model without mini-batching, then only making two changes: changing `lookup()` (with a single word ID) to `lookup_batch()` (with a list of word IDs for time step t), and `pickneglogsoftmax()` to `pickneglogsoftmax_batch()` similarly. It's hard to debug this without a full code example, so if this is still a problem after taking a look at the new mini-batch documentation, could you please open another issue with a full minimal reproducible example? Thanks!
