### ISSUE TITLE
Just-in-time parameter updates

### ISSUE THREAD

**Issue by jkkummerfeld** [clab/dynet#283]
I noticed in the DyNet paper (https://arxiv.org/pdf/1701.03980v1.pdf) on page 19 that just-in-time parameter updates are mentioned, and Pegasos is cited. Two notes:

1 - My understanding is that AdaGrad does actually require an update to weights with zero gradient. However, they can also be implemented just-in-time as described in [http://aclweb.org/anthology/D/D15/D15-1032.pdf](http://aclweb.org/anthology/D/D15/D15-1032.pdf).
2 - I haven't seen it anywhere, but by approximating epsilon as 0 in Adam, I think a closed form update for weights with gradient zero can be formed.

Is there any interest in adding this to DyNet? I'm guessing it would be of the "we'd accept a pull request" variety :) but whether it is worth implementing depends on the anticipated impact on speed.

**Comment by neubig** [comment]
Hi @jkkummerfeld . This is something we've talked about, and it would definitely be nice to have. The reason why this ended up getting put on the back-burner because we couldn't think of an easy way to do this without complicating the programming interface. If there's a way that we could do this without making things more complicated for users I think it'd be something worth considering, but I'm not sure whether there's an easy way to do so or not.

**Comment by neubig** [comment]
I think this likely will not be fixed? So I'm going to close it now. Contributions are still welcome though.
