### ISSUE TITLE
MKL empowered multithreading 

### ISSUE THREAD

**Issue by anglil** [clab/dynet#309]
I set MKL_DYNAMIC=FALSE without setting MKL_NUM_THREADS and multithreading works; TOP command shows more than one core is being used. However, once I set MKL_NUM_THREADS to any specific number, multithreading stops working; only one core would be used (CPU% ~ 100%). So my question is, in addition to MKL_NUM_THREADS, what other environment variables need to be set / what other actions need to be taken, to be able to specify the number of threads to use? Thanks!
-Angli

**Comment by neubig** [comment]
I'm not sure about this, but @mattr1 may know?

**Comment by anglil** [comment]
Thanks in advance @mattr1

**Comment by mattr1** [comment]
I'm not sure why it's not working properly for you. I just tried this myself in Windows and it works fine. However, according to the Intel documentation (https://software.intel.com/en-us/node/528547), they recommend that you don't set MKL_DYNAMIC to false unless needed. I leave it unset. Can you try leaving MKL_DYNAMIC not set, and then change the MKL_NUM_THREADS and see what happens? Also, there are these other variables that I leave unset, but perhaps they are set on your system, can you try unsetting them and see if it fixes your problem: OMP_DYNAMIC, OMP_NUM_THREADS, OMP_NESTED.

**Comment by anglil** [comment]
Thanks. I've tried all these combinations of these variables - It turns out that the only two configurations that worked for me are the following:
OMP_NUM_THREADS=2
OMP_NESTED=TRUE
MKL_DYNAMIC=FALSE

unset everything MKL and OMP, and then
MKL_NUM_THREADS=2
both of which led to CPU% = 200%.
Any configuration that's not any of these leads to just one core being used. Especially, when OMP_NUM_THREADS is set to any number other than 2, multi-threading won't happen.

But of course I only tested the encoder decoder example as shown below, so I don't have evidence as to whether these 2 are also the only configurations that will lead to parallelism for other applications:
./examples/train_encdec --dynet-seed 1 --dynet-mem 1000 -t ../examples/cpp/example-data/train-hsm.txt -d ../examples/cpp/example-data/dev-hsm.txt

Do you have any idea on why this is the case or insight into why encdec is special in this regard? Thanks!

**Comment by mattr1** [comment]
I would stick with option (b) -- that's what I've been doing and seen work fine with varying the number of threads. 

Okay, I think I found the problem. I just tried train_encdec myself and it's only using one core for me also. The problem is the default input and hidden dimensions are tiny (2 and 4, respectively)! So there is no option for MKL to multi-thread the matrix operations. Can you append "-h 200" to set the hidden size to 200, and try again? Also, I tried running train_nlm and it uses all the cores (e.g., train_nlm example-data/fin.txt).

**Comment by anglil** [comment]
Thanks! I replicated what's happened on your end after setting the hidden size to 200 and sticking with option (b). 
Final question, Is OpenMP introduced by installing MKL? If this is not the case, I wonder if using option (b) would affect parallelism in other applications or software that use multi-threading?  Thanks!

**Comment by mattr1** [comment]
On Windows at least, installing MKL also installs OpenMP libraries, since MKL depends on them (look for libiomp). I would presume that whether or not you have installed MKL, if you set the OMP environment variables, it would affect any program that uses OpenMP. I would also hope that setting MKL_NUM_THREADS would only affect MKL, not OpenMP. The best bet it to set MKL_NUM_THREADS in your local environment when you are using dynet, rather than setting it globally.

**Comment by anglil** [comment]
That's really helpful. Thanks for your input :-)
