### ISSUE TITLE
Retire matInput from python?

### ISSUE THREAD

**Issue by yoavg** [clab/dynet#346]
Following questions on #345 , and now that we have inputTensor, perhaps we should consider retiring matInput (replacing it with a blank op that throws an error and asks the user to switch to inputTensor).

We really don't need both functionalities, and the way inputTensor handles things is cleaner.
The difference in functionality I do see is that matInput supports setting a new value (for "static" graphs). We can either add this to inputTensor, or remove the functionality altogether.

**Comment by neubig** [comment]
I agree with this.

**Comment by pmichel31415** [comment]
By setting a new value do you mean calling `.set()` on a `_vecInputExpression` ? I believe that is also possible with `inputTensor` since it also returns a `_vecInputExpression` (unless I'm missing something)

If this is the case, then maybe it would be a good idea to add a `setTensor` method to set a new value via a numpy ndarray as well? From my own experience it's a bit unsettling as a first time user to have to flatten (with the right ordering) the input before feeding it to dynet, eg. when the input is a matrix or a batch of vectors.

**Comment by yoavg** [comment]
Yes, no need to require the user to call flatten. This was a bad design choice on my part when creating the initial python matrix inputs.

**Comment by pmichel31415** [comment]
Fixed by #606
