### ISSUE TITLE
Dynamically increasing memory pools

### ISSUE THREAD

**Issue by neubig** [clab/dynet#363]
This is something that would be really nice to have, but not super-easy to implement. Currently, DyNet requires you to specify how much memory you want to use at program initialization time. If you ever go over this, DyNet crashes and you basically have to stop your program.

TensorFlow gets around this by having memory pools that start small, but increase every time you allocate too much memory and go over the specified amount. It would be nice if we could do this in DyNet as well.

The main sticking point here is how to handle the pointers that are still around from before the memory pool was re-allocated. There are a number of ways that we could do this, perhaps by keeping track of the relative pointer compared to the start of the memory pool, or adjusting all of the pointers belonging to the old memory pool. Neither of these seems easy, but if someone wants to take a stab at it this might be worth doing.

**Comment by yoavg** [comment]
Check out the dynmem branch, it is a sketch of an attempt at this.

The idea is to keep a list of AlignedMempool (new renamed to InternalMempool), and when the current one is empty, create a new one and start using it. Then, when freeing the mempool, if we have more than 1 internal pool, the internal mempools are freed and we create a new large one instead.

I think this should work with minimal effect on speed, and with minimal change in code.

However, it is currently not compiling (so not tested) because `Device::revert()` is accessing `->used`. I believe it should be easily fixable, but am not sure what does `Device::revert()` do?

**Comment by neubig** [comment]
Wow, this is a brilliant idea!

Anyway, `Device::revert()` is used to roll-back the memory pool to a previous state. This is useful in scenarios where you might want to do some computation, then throw it away. For example, when doing beam search, you could calculate a softmax, choose which hypotheses you want to explore next, then `revert()` back to throw away the softmax, which you won't be using but is relatively memory intensive. I'm not sure if this is easily reconcilable...

**Comment by yoavg** [comment]
oh, it might be me who added this initially, then ;)
do you have any idea why I added it to Device and not to the mempools?

**Comment by neubig** [comment]
I think it was us who added this. And the reason why it was added to device is because we'd basically be rolling back the "state" of DyNet, and the state is expressed by all three of the memory pools, not just a single one.

**Comment by yoavg** [comment]
Ok, I pushed an update that should take care of this -- but did not have the time to test it yet, and gotta go now.

**Comment by yoavg** [comment]
hmm.. I did some minimal testing, and there seem to be an unexpected problem -- we now rely on the malloc in sys_alloc to return 0 when we are out of memory, and this doesn't really happen because the OS over-commits. Not sure how to resolve this.

**Comment by neubig** [comment]
I also did some testing here and it seems to be working great!

What do you mean about malloc? Does this mean that it's swapping?

**Comment by yoavg** [comment]
Try something that requires much more memory than you have, on the CPU.

**Comment by yoavg** [comment]
related to this I think:
http://stackoverflow.com/questions/7947849/can-i-rely-on-malloc-returning-null

**Comment by neubig** [comment]
Hmm, so this is just a problem of Linux programs in general? My understanding is that before this becomes a problem the program will generally start swapping, and users will kill it appropriately, right? Maybe I'm misunderstanding the problem, or misunderstanding the gravity of the problem?

If this is not a big problem, I think this would be a really useful addition, so I'll do some performance testing to make sure it's not hurting performance and then we can merge.

**Comment by neubig** [comment]
FYI, I tested this on CPU/GPU and there's basically no performance hit from what I could tell. If the problem of malloc returning non-zero values on failure is not a major one, I think we can go ahead and merge this. This is super-useful.

**Comment by yoavg** [comment]
I think the property of the process failing on lack of memory (instead of potentially causing other processes to die) is actually desirable in multi-user environments, and it also a good indicator that things are not working properly. But I also realize the benefits of the automatic allocation. Maybe we can add a switch to allow a "hard memory limit", which will be set by default to 500GB or something.
In any case, this can come later, after the current merge.

I do however worry that this code is not properly tested---in particular I did not test the revert() functionality at all (in particular after allocation), and suspect this can be buggy. So merge at your own risk.

**Comment by neubig** [comment]
OK, I noted it here: https://github.com/clab/dynet/pull/364

I agree that we should probably do more testing, including unit tests.

**Comment by neubig** [comment]
Resolved by https://github.com/clab/dynet/pull/364
