### ISSUE TITLE
runtime checking may slow down dynet

### ISSUE THREAD

**Issue by Oneplus** [clab/dynet#374]
Currently, dynet do runtime checking on the forward/backward (dimension, input indices, etc.) at any circumstance. And the time consumption is non-trivial. I've tried blinding the LookupNode::forward by removing such checking (line: 257-258 in param-nodes.cc) and it led to less running time (8800+ ms to 8300+ ms on 1000000 lookups, code below).

It would be great to let the user decide whether performing runtime checking. In some circumstance, the user would be sure that their network's dimensions are correctly configured and everything is right with their data.

reference code:
```
  dynet::Model m;
  dynet::LookupParameter p_W = m.add_lookup_parameters(n_entries, { n_dim });
  for (unsigned i = 0; i < embeddings.size(); ++i) { p_W.initialize(i, embeddings[i]); }

  unsigned n_repeat = boost::lexical_cast<unsigned>(argv[2]);
  unsigned n_tests = boost::lexical_cast<unsigned>(argv[3]);
  unsigned n_batch = boost::lexical_cast<unsigned>(argv[4]);
  std::vector<std::vector<unsigned>> tests(n_tests, std::vector<unsigned>(n_batch));
  for (unsigned t = 0; t < n_tests; ++t) {
    for (unsigned b = 0; b < n_batch; ++b) { tests[t][b] = ((*dynet::rndeng)()) % n_entries; }
  }
  auto time_start = std::chrono::high_resolution_clock::now();
  unsigned t = 0;
  std::cerr << "start testing" << std::endl;
  for (unsigned repeat = 0; repeat < n_repeat; ++repeat) {
    dynet::ComputationGraph cg;
    dynet::expr::Expression emb = dynet::expr::lookup(cg, p_W, tests[t]);
    std::vector<float> v = dynet::as_vector(cg.get_value(emb));
    std::cout << v[0] << std::endl;
    t++;
    if (t == n_tests) { t = 0; }
  }
  auto eclipsed = std::chrono::high_resolution_clock::now() - time_start;
  std::cerr << "consume time: " << std::chrono::duration<double, std::milli>(eclipsed).count() << std::endl;
```

**Comment by neubig** [comment]
This is a good point. I think there should probably be two levels of controlling debug checking:
- User debug mode: On by default, but able to be turned off. Checks for things like invalid arguments and mismatched dimensions.
- Developer debug mode: Off by default, turns on things like asserts.

To make it possible to turn off user debug checks, I think we could probably change `DYNET_INVALID_ARG` so that it explicitly performs a check, and throws an error if necessary. If user debug mode is turned off, this macro will instead do nothing.

To make it possible to turn off developer debug checks, we'll need to add `-DNDEBUG=1` to the compile-time flags, and also change `DYNET_ASSERT` to do nothing when debugging is off.

**Comment by neubig** [comment]
Fixed by https://github.com/clab/dynet/pull/375
