### ISSUE TITLE
generalized concatenate, transpose, and batchify operations

### ISSUE THREAD

**Issue by redpony** [clab/dynet#390]
It would be nice to be able to convert a sequence of vectors to a batch of vectors, or a sequence of matrices to a batch of matrices. Right now we have concatenate and concatenate_cols, but in general, we probably want an operation like numpy's concatenate that works on sequences of tensors of arbitrary size and takes an index of concatenation.

`concatenate({a, b, c}, 0)` would be equivalent to `concatenate({a, b, c})`.

`concatenate({a, b, c}, 1)` would be equivalent to `concatenate_cols({a, b, c})`.

A generalized transpose would work similarly. `tranpose(a, {1, 0})` would be usual transposition, but you could also do things like `transpose(a, {2, 0, 1})` for higher order tensors.

We should keep the old APIs around for backward compatibility and for readability, but they might just delegate to the generalized API.

Finally, it would be nice to be able to "batchify" a tensor. `batchify(a, n)` would take the leading n dimensions of `a` and make a batch of size `(d1 * d2 * ... * dn)` with dim `(d_n+1 x d_n+2 x ... x d_D)`.

**Comment by neubig** [comment]
Here is a checklist:
- [ ] concatenate function
- [ ] transpose function
- [ ] batchify function

I have a question about the batchify function: Because of how memory is laid out in Eigen, it's actually possible to do this using the `reshape` function when we're interested in batching the *trailing* dimensions (not leading dimensions) by just doing:

    reshape(Dim({d1, d2, ..., dn}, dn+1 * dn+2 * dn+3 * ...)

Would this be sufficient?

**Comment by neubig** [comment]
I'm going to close this as the need for batchify is not entirely clear, but feel free to reopen if necessary.
