### ISSUE TITLE
DyNet Benchmark Examples cudaMemcpy Error

### ISSUE THREAD

**Issue by ilkerkesen** [clab/dynet#455]
Hi,

I've tried to run DyNet examples (used for benchmarking in the report), but they do not work. Right now, I am using sequence-ops branch of DyNet. By the way, I tried to run Python examples distributed with DyNet, and they just work without any problem. [This](https://gist.github.com/ilkerkesen/8c4fc18975776ace35efe7f470361cd7) is the output. The benchmark examples run on CPU without any problem, too.

Is there any public Amazon AMI for these benchmarks? I've found an AMI at Oregon, but I think it does not belong to these benchmarks and I still couldn't have made them working. It gives still the same error.

I've opened this issue on dynet-benchmark repo. However, since I've got no response yet for nearly two months, I'd like to open the same issue on here based on an advice given by Yoav. He thought that more people will look at this one. Thanks.

**Comment by neubig** [comment]
Sorry, not sure what's going on here, but I'll look into it...

**Comment by neubig** [comment]
So because the sequence-ops branch is pretty old, I'd suggest trying to run with the most recent master version of DyNet. I've modified the benchmarks so that they should compile even without the sequence-ops branch. Would you mind trying with the most recent version and still get the error? If so, could you tell us the exact command that you ran to do it? Thanks!

**Comment by neubig** [comment]
No word on this, so I'll close for now. Please tell me if it's still an issue.
