### ISSUE TITLE
LSTM without update

### ISSUE THREAD

**Issue by jihelhere** [clab/dynet#538]
Hi,

I can't find a way to use an LSTM in a deep architecture without updating its parameters during backprop (for instance in a GAN scenario where an LSTM is used as a discriminator).

if RNN/LSTM methods new_graph/new_graph_impl could take an additional boolean flag, 
then internal parameters could be passed as const_parameter if needed.

**Comment by neubig** [comment]
The easiest way to do this is to add a `nobackprop()` operation between the LSTM and whatever you're trying to use it to calculate. Will this solve your problem?

**Comment by jihelhere** [comment]
I'm not sure,

I would like error to backpropagate through the LSTM down to the lower layers of the architecture as usual. I just don't want the lstm parameters to be updated when the trainer calls update.
IIUC, nobackprop would prevent the error to propagate down the network.

**Comment by pmichel31415** [comment]
This should be rather easy to add.

I don't have a lot of time to do it right now though, but if you want to contribute here's what needs to be done : 

- in file `dynet/rnn.h` : change the interface of `RNNBuilder::new_graph` to take an additional optional boolean parameter `update`, by default set to `true`
- in files `dynet/rnn.*`, `dynet/lstm.*`, `dynet/gru.*`, `dynet/fast-lstm.*`, `dynet/deep-lstm.*` : update the interface to add the new parameter and change the `new_graph_impl` method to use `const_parameter` instead of `parameter` depending on the `update` parameter ([here for the lstm for example](https://github.com/clab/dynet/blob/master/dynet/lstm.cc#L57-L69))
- Update the documentation (doxygen comments)
- Optional : add tests in `tests/test-rnn.h`
- Update the python bindings : 
    - Change [this line](https://github.com/clab/dynet/blob/master/python/_dynet.pxd#L418) to take the new parameter into account
    - And [this function](https://github.com/clab/dynet/blob/master/python/_dynet.pyx#L3316-L3318) and [these](https://github.com/clab/dynet/blob/master/python/_dynet.pyx#L3404-L3451)

This would be super helpful!

If you don't have time I'll do it but not before the end of next week.

**Comment by jihelhere** [comment]
Thanks!

I can do this next week.

**Comment by jihelhere** [comment]
Working on the code, I wonder if this could be the opportunity to refactor the `parameter`  method so it would take an additional parameter to signify whether it's "trainable" or not. In this case `const_parameter` would be just a wrapper that sets this boolean to false.
 
I am under the impression that the python bindings already do something like that with `expr`

With the current implementation, it requires either to first declare parameter expressions before they are set to  const/non const in RNN constructors for scoping reason, or to set the vector of parameters in both branches of the `if` test. This is rather ugly.

 Another possibility would be to use the ternary operator, for instance: 
`Expression i_x2i = update ? parameter(cg,p[X2I]) : const_parameter(cg, p[X2I]);` 
This would be my preferred solution, but  don't know enough about dynet coding style to tell if it's ok. A drawback is that it requires a test for each parameter.

**Comment by pmichel31415** [comment]
I think for now using the ternary operator would be OK.

**Comment by pmichel31415** [comment]
fixed by #547
