### ISSUE TITLE
Bug in conv2d test case on GPU

### ISSUE THREAD

**Issue by pmichel31415** [clab/dynet#594]
I ran `test-nodes.cc` with a CUDA/CuDNN enabled version of dynet to check on something else and I noticed the following error:

    ~/dynet/tests/test-nodes.cc(1245): error: in "node_test/conv2d_same_gradient": check check_grad(mod, z, 0) has failed

@zhisbug any ideas?

**Comment by zhisbug** [comment]
I am aware of this issue (as I wrote the test case by myself). However, I compared my result with TensorFlow (with same input) -- they are consistent. You can increase the verbosity level of grad check function and see the printout. I suspect it is caused by some numeric issues in the grad_check function.

**Comment by neubig** [comment]
If that's the case, one way we could fix this is by ensuring that the inputs to the `conv2d` test are large enough to make sure that the gradients don't suffer from numerical instability. We should definitely check this though. The conv2d operation doesn't seem inherently instable, and because tests are passing on CPU I think it's unlikely that it would be a problem that only appears on GPU. Of course I may be wrong.

**Comment by zhisbug** [comment]
I think I have figured out the problem. The gradient computation is correct (no worry!). The test case does not pass on GPU because some irrelevant (and unused) parameters are overwritten (we create 5 model parameters in the test-node.cc code, some of them are not used when running this test case). It might be caused by some wild pointers but I am not sure at this point. I will have a fix tomorrow.

**Comment by pmichel31415** [comment]
good to know! Yeah I found it weird, especially since the GPU implementation is straight from cudnn

**Comment by zhisbug** [comment]
After 2 days' debugging, I ended up with the following conclusion. This is actually not a bug. This is caused by cuDNN's non-determinism. 

I run the following simple test: I feed the same feature maps and filter parameters into cuDNN and call forward (or backward) for multiple times, the output by different calls will be slightly different (no matter I launch DyNet multiple times or have multiple calls using a for loop within one launch). This explains why the approximated gradients of some irrelevant parameters will be non-zero sometimes (i.e. grad_check not pass.).

This is also a known issue in other communities. Fortunately, I haven't seen any report saying this will affect the statistical convergence.

**Comment by zhisbug** [comment]
Beside this known issue, I will have a PR to fix some other issues (I found during debugging).

**Comment by neubig** [comment]
OK, sounds good. Good to know the problem at least. Perhaps we can add a test that doesn't rely on the gradient checking.
