### ISSUE TITLE
When compiling on CUDA, unnecessary compute architectures are generated

### ISSUE THREAD

**Issue by neubig** [clab/dynet#661]
On this line, we are specifying that CUDA should compile on a bunch of different computation architectures from `compute_30` co `compute_52`:
https://github.com/clab/dynet/blob/master/dynet/CMakeLists.txt#L125

In most cases, we probably only need to compile on a single computing architecture, the most recent one supported by the `nvcc` compiler and GPU. Because compiling for different architectures takes a long time and is a significant time bottleneck in getting DyNet installed on GPU, it would be nice to fix this. I'm not sure how to do so though, so if someone knows how help would be appreciated.

**Comment by mattr1** [comment]
I found compiling just for architecture 5.2 makes the compilation roughly twice as fast. The only way I can think of is a parameter passed to cmake telling it what architecture the user wants, with a suitable default (maybe default to all the architectures, as it is currently done, so that people who are just compiling once will have a library that runs everywhere). We could have a page in the documentation on speeding up compilation, or a page for developers, describing options like this.
