### ISSUE TITLE
Better model saving/loading

### ISSUE THREAD

**Issue by neubig** [clab/dynet#84]
Currently, cnn models use model the boost serialization library to perform model saving/loading. This is easy, but only works if you use the same version of boost to save/load files. Ideally, we can create a version of model saving that works across boost versions, perhaps by creating a custom boost serializer that reads/writes the parameters appropriately in text format.

**Comment by honnibal** [comment]
I found the Boost version stuff the trickiest part of installing the library.

Is it possible to remove the dependency on Boost altogether? Does Eigen need Boost deeply, or only for serialization?

If the Boost dependency could be dropped, the library could be packaged for PyPi, so that "pip install dynet" would work.

**Comment by neubig** [comment]
Model saving/loading relies on boost, so until this issue is resolved, the
dependency to boost definitely cannot be removed. Serialization is the main
place where it's being used, but it looks like there is also code for
threaded computation and calculation of the digamma function that uses
boost and may not be trivial to remove.

Of course, reducing reliance on external libraries is generally a good
thing, and with c++11 we can largely live without boost, so it might be
something to think about.

**Comment by neubig** [comment]
We are currently considering a YAML-based approach to improving model saving/loading in DyNet. Using a library such as this may be useful: https://github.com/jbeder/yaml-cpp

**Comment by xunzhang** [comment]
I think YAML format is more readable and easy to maintain as an independent module. By using these popular formats we could also deal with different languages. But I suggest considering some official libraries together with their performance.

Since this work relates to lots of development and refactoring work, please try to give a proposal first(for example, use YAML format..) and then people from the community could contribute, in case no contributions are conflicted or in vain. Thanks.

**Comment by neubig** [comment]
Thanks for the comment @xunzhang . I did post this in hope of keeping people informed. One thing that we've been thinking about a little bit is whether to rehaul the overall model saving/loading API, or to just do a simple fix of the current code. Here are details of the two options: 

--- Simple fix
Probably the shortest path to doing this would be to re-write something very similar to boost::archive::text_iarchive that instead is implemented directly in DyNet and outputs YAML.

--- More complicated fix
Something that might be nicer would be to re-haul the model format a little bit so that it outputs things in a more easy-to-read format where the model specification (structure of builders, etc.) is written out first, then the data comes later in the file. This means that people could open the file without being overwhelmed by the model parameters themselves.

With regards to comparing official YAML libraries, I think this is something that could be done, but I've heard good things about yaml-cpp. If anyone else has experience I'd love to hear.

**Comment by neubig** [comment]
Fixed by https://github.com/clab/dynet/pull/637
