### ISSUE TITLE
Dividing loss by batch size when using manual minibatching?

### ISSUE THREAD

**Issue by johntzwei** [clab/dynet#972]
Hi! For manual minibatching, I was wondering whether I needed to divide my loss by the batch_size after using dy.sum_batches or is that done for us? What about autobatching? Thanks!

**Comment by pmichel31415** [comment]
Hi. No dynet does not do it for you. You can use [`dy.mean_batches`](http://dynet.readthedocs.io/en/latest/python_ref.html#dynet.mean_batches) instead of sum_batches.

Notice that if your batch size is the same for all minibatches then dividing the final loss by the batch size is equivalent to decreasing the learning rate so you shouldn't need to do it provided you tune the learning rate properly.
